import { defineConfig } from "orval";

export default defineConfig({
  eventGoAPI: {
    input: "./eventgo.yml",
    output: {
      target: "apis",
      mode: "tags",
      workspace: "src/openapi",
      schemas: "models",
      client: "swr",
      clean: true,
      override: {
        mutator: {
          path: "./fetcher.ts",
        },
        header: () => [
          "Generated by Orval",
          "Do not edit manually",
          "See `gen:api` script in the package.json",
        ],
      },
    },
  },
});
