/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * EventGo API
 * API documentation for EventGo application
 * OpenAPI spec version: 1.0.0
 */
export interface Event {
  id?: string;
  name?: string;
  date?: string;
  location?: string;
  description?: string;
}

