/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * EventGo API
 * API documentation for EventGo application
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Event
} from './eventGoAPI.schemas';





  /**
 * @summary Get all events
 */
export const getAllEvents = <TData = AxiosResponse<Event[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/events`,options
    );
  }
/**
 * @summary Get event by ID
 */
export const getEventById = <TData = AxiosResponse<Event>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/events/${id}`,options
    );
  }
export type GetAllEventsResult = AxiosResponse<Event[]>
export type GetEventByIdResult = AxiosResponse<Event>
