import {
  ChatAndNetwork,
  Home,
  NotFoundPage,
  UserDashboard,
  AdminDashboard,
  EventDiscoveryPage,
  Profile,
  CreateEvent,
  Onboarding,
  ProfileSetup,
  Events,
  Mentors,
  MentorProfile,
  Settings,
} from "../pages";
import { IRoute } from "../../interfaces/Route";

export const routes: IRoute[] = [
  {
    path: "/events",
    title: "event list",
    component: Events,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/mentors",
    title: "mentors list",
    component: Mentors,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/",
    title: "home page",
    component: Home,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/onboarding",
    title: "Registration",
    component: Onboarding,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/admin-dashboard",
    title: "Admin Dashboard",
    component: AdminDashboard,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/event/:id",
    title: "Event Details",
    component: EventDiscoveryPage,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/mentor/:id",
    title: "Mentor Profile",
    component: MentorProfile,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/dashboard",
    title: "Dashboard",
    component: UserDashboard,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/profile-setup",
    title: "Profile Setup",
    component: ProfileSetup,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/inbox",
    title: "Messages",
    component: ChatAndNetwork,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/profile",
    title: "Profile",
    component: Profile,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/start",
    title: "Create Event",
    component: CreateEvent,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "/settings",
    title: "Settings",
    component: Settings,
    type: "protected",
    menu: {},
    isStandalone: true,
  },
  {
    path: "*",
    title: "Not Found",
    component: NotFoundPage,
    type: "unproteted",
    menu: {},
    isStandalone: true,
  },
];
