/**
 * Generated by Orval
 * Do not edit manually
 * See `gen:api` script in the package.json
 */

export interface Event {
  id?: string;
  name?: string;
  date?: string;
  location?: string;
  description?: string;
}
